project_id: 401640
api_token_env: CROWDIN_TOKEN
preserve_hierarchy: true

files:
  - source: /docs/*.md
    translation: /docs/%locale_with_underscore%/%original_file_name%
  - source: /docs/.vitepress/i18n/strings/en_US.json
    translation: /docs/.vitepress/i18n/strings/%locale_with_underscore%.json
  - source: /docs/public/assets/images/sdroot/en_US.png
    translation: /docs/public/assets/images/sdroot/%locale_with_underscore%.png
